#!/usr/bin/env python3
"""Generate /data/.relay/node.yaml from the ha-exec.py CAPS table.

Single source of truth: ha-exec.py defines the capability matrix (names,
versions, payload fields). This bootstrap mirrors it into the node profile
the daemon publishes at registration — no hand-maintained second table.

Input: JSON array of {name, version, description} from ha-exec --caps-json.
Output: node.yaml with handler = "python3 /usr/local/bin/ha-exec.py".
"""
import json
import sys

HEADER = """\
# node.yaml — auto-generated by iowap-ha bootstrap (do not edit; regenerate
# via run.sh on app start). Capabilities mirror the CAPS table in ha-exec.py.
"""


def main() -> None:
    caps = json.load(sys.stdin)
    lines = [HEADER, "node_name: IOWAP HA Node", "capabilities:"]
    for c in caps:
        lines += [
            f"  - name: {c['name']}",
            f"    version: \"{c.get('version', '1.0.0')}\"",
            f"    description: {c.get('description', c['name'])}",
            "    auto_publish: true",
            "    claimable: true",
            "    handler: python3 /usr/local/bin/ha-exec.py",
            "    max_parallel: 1",
            "    timeout: 60",
        ]
    sys.stdout.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()