#!/usr/bin/env python3
"""Generate /data/.relay/node.yaml from the ha-exec.py CAPS table.

Single source of truth: ha-exec.py defines the capability matrix (names,
versions, payload fields). This bootstrap mirrors it into the node profile
the daemon publishes at registration — no hand-maintained second table.

Input: JSON array of {name, version, description} from ha-exec --caps-json.
Output: node.yaml with handler = "python3 /usr/local/bin/ha-exec.py".
"""
import json
import sys

HEADER = """\
# node.yaml — auto-generated by iowap-ha bootstrap (do not edit; regenerate
# via run.sh on app start). Capabilities mirror the CAPS table in ha-exec.py.
"""


def main() -> None:
    caps = json.load(sys.stdin)
    lines = [HEADER, "node_name: IOWAP HA Node", "capabilities:"]
    for c in caps:
        lines += [
            f"  - name: {c['name']}",
            f"    version: \"{c.get('version', '1.0.0')}\"",
            f"    type: {c.get('type', 'tool')}",
            # block scalar: keeps multi-sentence descriptions one string,
            # immune to YAML-breaking punctuation in the docs text
            f"    description: >-",
            f"      {c.get('description', c['name'])}",
            "    auto_publish: true",
            "    claimable: true",
            "    handler: python3 /usr/local/bin/ha-exec.py",
            "    max_parallel: 1",
            "    timeout: 60",
        ]
        schema = c.get("input_schema")
        if isinstance(schema, dict) and schema.get("fields"):
            lines.append("    input_schema:")
            lines.append("      fields:")
            for fname, fs in schema["fields"].items():
                lines.append(f"        {fname}:")
                for key, val in fs.items():
                    if val is None:
                        continue
                    if isinstance(val, bool):
                        lines.append(f"          {key}: {str(val).lower()}")
                    else:
                        lines.append(f"          {key}: {json.dumps(val)}")
    sys.stdout.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()